### ISSUE TITLE
Vertalingen Frans (Files aanmaken en vertalingen uitvoeren)

### ISSUE THREAD

**Issue by JornHeyvaert** [TTCErembodegem/TTC-React-Front#109]
Jorn zal deze files (locales.en... en locales.fr....) aanmaken in utils folder en vertalingen uitvoeren
-> gewone vertalingen + vertaling van Feiten pagina

**Comment by Laoujin** [comment]
Hey Jorn,

Veel vertalingen hebben we momenteel dubbel, zou goed zijn om dat eens te reconciliëren zodat we alles maar 1 keer hebben
Vb: Adres, Naam, Beste slag, Gsm, ...


Er zal dan ook user settings moeten komen en een switch om de taal aan te passen in het profiel ergens

**Comment by JornHeyvaert** [comment]
Vertalingen gedaan :)
Hoe gaan we deze nu toepassen?

**Comment by Laoujin** [comment]
ah jammer... ik was net bezig met een opkuis

**Comment by JornHeyvaert** [comment]
gewoon opkuizen in beide locales wat je al hebt verwijderd?

**Comment by Laoujin** [comment]
er zijn redelijk wat dubbels
sommige dingen staan niet op de juiste plaats

ma ik zal het ook aanpassen in de FR.

**Comment by JornHeyvaert** [comment]
Ahzo ok, dan moeten we eens zien hoe we het gaan toepassen e :)

**Comment by Laoujin** [comment]
If no cookie:
check de current culture in javascript en
If FR --> FR
Else --> NL
--> set as cookie

Switchen tussen talen:
--> laadt de locales uit de juiste file
--> Zet de locale van momentjs

Taal manueel wijzigen:
Voeg ergens iets subtiel toe. Mss in de footer?

**Comment by Laoujin** [comment]
Het leukste zal wel worden om de volledige site dan opnieuw te testen in FR en dan de FR vertalingen en/of layout aan te passen zodat alles er deftig uitziet op de verschillende mobile devices.

(doordat sommige FR nu langer zijn dan de oorspronkelijke NL vertalingen zullen er hier nog heel wat wijzigingen voor nodig zijn wss)

**Comment by Laoujin** [comment]
Ik heb de twee locales gesynced...

**Comment by Laoujin** [comment]
Met dat Sami weg is en dat het niet mogelijk is om de site in het frans te tonen heb ik de franse vertalingen gedelete.
