### ISSUE TITLE
Website isn't showing anything at the moment due to errors (I suppose)

### ISSUE THREAD

**Issue by JornHeyvaert** [TTCErembodegem/TTC-React-Front#146]
**Voorbeelden:**

![image](https://user-images.githubusercontent.com/10796411/42946855-40bc54e0-8b6c-11e8-8fbd-b762ab4df6fb.png)

![image](https://user-images.githubusercontent.com/10796411/42946869-4aca68d2-8b6c-11e8-930e-95a0acd52aff.png)

![image](https://user-images.githubusercontent.com/10796411/42946917-682369ec-8b6c-11e8-82a1-08ad5b3aae9d.png)

**Error messages in de console:**

![image](https://user-images.githubusercontent.com/10796411/42946983-8aa1a826-8b6c-11e8-9e56-5c8559e621e0.png)

**Warning messages in de console:**

![image](https://user-images.githubusercontent.com/10796411/42947029-ac21468c-8b6c-11e8-98e3-02a4db356d70.png)

Misschien eens bekijken want voorlopig toont de website maar zeer weinig :p

**Comment by JornHeyvaert** [comment]
Meer details van de error:

![image](https://user-images.githubusercontent.com/10796411/42947197-15eafd24-8b6d-11e8-913a-1c25f0a942d8.png)

**Comment by Laoujin** [comment]
I know...

ClearDB facturatie gebeurd niet meer door Azure maar gaat nu rechtstreeks. Zij hebben mijn facturatiegegevens niet en omdat er vorige maand niet betaald is hebben ze de database afgesloten.

Ik ben dus van plan
* wanneer ik geen tijd heb om bij ClearDb mijn facturatie gegevens te gaan invullen
* wanneer ik wat tijd heb om over te schakelen naar Sqlite om zo de hosting kosten naar beneden te halen.
