### ISSUE TITLE
Training starts at 19u30 instead of 20u 

### ISSUE THREAD

**Issue by JornHeyvaert** [TTCErembodegem/TTC-React-Front#147]
Ik heb de training aangepast van 20u naar 19u30 naar aanleiding van de mail van een paar weken geleden:

"Zoals reeds eerder gemeld spelen we elke dinsdag en donderdag van 19u30 tot 23u00" 

De mensen die de tafels klaarzetten op training gaan ons dankbaar zijn voor deze kleine change :D

**Comment by Laoujin** [comment]
Dit zit in de database en is reeds aangepast

**Comment by JornHeyvaert** [comment]
@Laoujin 

Waarom zie ik dan dit op de site?

![image](https://user-images.githubusercontent.com/10796411/42949217-909bc586-8b71-11e8-8f69-589cf800400f.png)

**Comment by Laoujin** [comment]
Hmm duplication...

**Comment by JornHeyvaert** [comment]
Staat nog steeds hardcoded trouwens in file \src\components\App\Intro.js:

![image](https://user-images.githubusercontent.com/10796411/42949404-fb95ceb8-8b71-11e8-852a-1340ed256789.png)

**Comment by JornHeyvaert** [comment]
@Laoujin 

Ik heb een quick fix die 20u verandert naar 19u30 in de locales in mijn branch? 
Mergen?
