### ISSUE TITLE
UI Issue: Link 'Paswoord vergeten' rendert niet ok op PC en Mobile

### ISSUE THREAD

**Issue by JornHeyvaert** [TTCErembodegem/TTC-React-Front#152]
Voorbeelden:

PC:

![image](https://user-images.githubusercontent.com/10796411/45928364-a1e9c900-bf42-11e8-8f34-d34ce8416b5e.png)

Mobile:

![image](https://user-images.githubusercontent.com/10796411/45928370-bded6a80-bf42-11e8-8755-2bb1514df88a.png)

**Comment by Laoujin** [comment]
Ik had het ook gezien.

Een pull request maken voor zoiets is misschien sneller gedaan dan de screenshots nemen enzo? :)

**Comment by Laoujin** [comment]
En, wat denk je... Kun je een Pull Request maken?
