### ISSUE TITLE
Nieuwe klassementen Sporta aanpassen (Naar echte waarden ipv schatting) op Home page

### ISSUE THREAD

**Issue by JornHeyvaert** [TTCErembodegem/TTC-React-Front#160]
Schatting:

![image](https://user-images.githubusercontent.com/10796411/56303747-e508c500-613c-11e9-9b6a-d47b3bf9e9b4.png)

Echte wijzigingen:

![image](https://user-images.githubusercontent.com/10796411/56303823-184b5400-613d-11e9-8256-2a436a7b922d.png)

Het zorgde al voor verwarring bij sommigen :p

**Comment by Laoujin** [comment]
oei! Maarten is opeens maar C4 meer
Of misschien goed... Dan kan hij volgend jaar weer stijgen :)
