### ISSUE TITLE
vertalingen

### ISSUE THREAD

**Issue by Laoujin** [TTCErembodegem/TTC-React-Front#17]
alle strings in the frontend uit json (voor frans, engels en arabisch:)
checken welke library geschikt is

**Comment by JornHeyvaert** [comment]
Vermits het waarschijnlijk een JS library moet zijn (anders resources in .NET e):
- http://i18next.com/
- http://keith-wood.name/localisation.html (JQuery)
- https://github.com/Marak/translate.js

Mij lijkt die eerste wel interessant

**Comment by Laoujin** [comment]
Vertalingen accessen:

```
import { contextTypes } from '../../../utils/decorators/withContext.js';

export default class SomeComponent extends Component {
  static contextTypes = contextTypes;
  ...
}

this.context.t('players.title', {a: 5});
```

De nl strings staan in `src/utils/locales-nl.js`:

```
export default {
  lang: 'nl',
  trans: {
    fullClubName: 'TTC Erembodegem',
    nav: {
      players: 'Spelers'
    },
    players: {
      title: 'Spelers overzicht {a}'
    }
  }
};
```
