### ISSUE TITLE
Tactiek voor tegenstanders

### ISSUE THREAD

**Issue by JornHeyvaert** [TTCErembodegem/TTC-React-Front#35]
Extra kolom toevoegen aan de tab tegenstanders in de matchen met als header 'Hoe tegen te spelen' (of andere manier?).
Hier komt dan een tekstveld in die kan bekeken worden en aangepast worden voor ingelogde users

**Comment by Laoujin** [comment]
wijzigingen nodig:
-> niet enkel de TTC Erembodegem spelers in spelers tabel
-> InitialLoad enkel de TTC Erembodegem laden
-> Extra kolom "WeakSpot" ofzoiets
-> Geen extra kolom --> want dat gaat niet lukken op mobile
-----> mss een icon (light gray=no comment yet; zwart=er is een weakspot ingevuld)
-----> op klikken = de rij openklikken (zoals bij laatste 5 matchen tegenstanders) en daar dan een Medium-Editor toevoegen?

**Comment by Laoujin** [comment]
dit is iets dat we mss kunnen doen wanneer de site echt gebruikt wordt...
