### ISSUE TITLE
Foto's worden niet goed getoond op volledig scherm (niet mobile)

### ISSUE THREAD

**Issue by JornHeyvaert** [TTCErembodegem/TTC-React-Front#36]
Foto's worden deels afgeknipt op volledig scherm waardoor sommigen er met een half (of drie kwart) gezicht opstaan.
Mobile is het in orde.

![image](https://cloud.githubusercontent.com/assets/10796411/13826308/0cec3a6a-ebb7-11e5-96ba-d23a11ad0e77.png)

**Comment by Laoujin** [comment]
Ah bugje... :)
Heb de foto gallerij nu bijgewerkt (met die bugfix)

Date: Wed, 16 Mar 2016 12:38:43 -0700
