### ISSUE TITLE
Onderste sponsors verdwijnen op mobiel op startpagina

### ISSUE THREAD

**Issue by JornHeyvaert** [TTCErembodegem/TTC-React-Front#37]
Geen mogelijkheid tot scrollen blijkbaar

![image](https://cloud.githubusercontent.com/assets/10796411/13850201/47578ef0-ec59-11e5-8dc8-a0121a30b67e.png)

**Comment by Laoujin** [comment]
dit was mijn "oplossing" voor het goed te krijgen op mobile... ze gewoon niet tonen :)
(en enkel de 2 belangrijkste sponsers wel te tonen)

als jij ze er nog wil bijzetten... be my guest (Bart en Jan zullen content zijn:)
