### ISSUE TITLE
IPhone: Left menu cannot be closed (icon not visible anymore to close it)

### ISSUE THREAD

**Issue by JornHeyvaert** [TTCErembodegem/TTC-React-Front#40]
Hey Jorn,
Ik krijg op geen enkele manier de linker 'keuze'kolom weg?
Checked met Iphone.
Zie foto...

![image](https://cloud.githubusercontent.com/assets/10796411/13899268/5a9f7292-edea-11e5-81c9-94aa67ce9acd.png)

Patrick De Smet

**Comment by Laoujin** [comment]
Bug: enhanceWithClickOutside werkt niet meer (of niet op iPhone)

**Comment by JornHeyvaert** [comment]
Och ja, nu hebben ze dan ook de mogelijkheid om de menu te sluiten via de menu zelf e. Is misschien ook wat duidelijker voor een gebruiker

**Comment by Laoujin** [comment]
Ik heb deze gefixed (https://github.com/TTCErembodegem/TTC-React-Front/commit/fc4d1020a0abbcf75ab695908304d9b610e47817)

vraag is nu natuurlijk of het op iPhone wel ooit gewerkt heeft want er was al wat hacky code rond die Navigatie geschreven

**Comment by Laoujin** [comment]
en een "X"je vanboven rechts in het menu zou mss mooier zijn?

**Comment by JornHeyvaert** [comment]
Mooier misschien wel , maar duidelijker lijkt mij niet
