### ISSUE TITLE
View van matchen van vandaag (Live matchen view) : Score komt boven titel op mobile

### ISSUE THREAD

**Issue by JornHeyvaert** [TTCErembodegem/TTC-React-Front#44]
![image](https://cloud.githubusercontent.com/assets/10796411/13982556/13b1b364-f0eb-11e5-9955-0dc1285f1947.png)

-> Voorstel : Score onderaan titel zetten vanaf een bepaalde grootte

**Comment by Laoujin** [comment]
is een todo bij mij:
- op TV laten zoals het is
- op kleinere devices de gewone match cards tonen + indien de score kan geupdate worden, de +/- daar ook
