### ISSUE TITLE
Percentages overwinningen/nederlagen verkeerd in Opstelling tab: Onlogische minwaarden voor nederlagen/overwinningen

### ISSUE THREAD

**Issue by JornHeyvaert** [TTCErembodegem/TTC-React-Front#45]
![image](https://cloud.githubusercontent.com/assets/10796411/13982615/68a13d68-f0eb-11e5-828b-0c25d36f8059.png)

**Comment by Laoujin** [comment]
Wat denk je... Neem jij deze op om te zien wat er daar aan de hand is?

**Comment by JornHeyvaert** [comment]
Oorzaak is volgens mij dat matchen waar de tegenstander er niet is (eigelijk FF) ook worden meegerekend als overwinning

**Comment by Laoujin** [comment]
Fix jij em of ik?

**Comment by JornHeyvaert** [comment]
Pak jij em als je wilt. Heb gisteren de syncer laten lopen, maar ik heb geen data met minwaarden dus kan het maar half testen. Ik zal mij terwijl bezighouden met de 'alle' view aan te passen aan jouw comments en dan te committen :)

**Comment by Laoujin** [comment]
hmm zet er de volgende keer het match id mss bij
was dat op de azure of lokaal bij jou?

**Comment by JornHeyvaert** [comment]
Op azure. Sint-niklase c tegen onze d-ploeg van afgelopen maandag

**Comment by Laoujin** [comment]
sint niklaze id = 12
dan ons team id opzoeken
dan zien welke competitie
afgelopen maandag... das dan 21/3
id is 17 631

als je bugs rapporteert (hier of op het werk), breng dan zoveel mogelijk info mee.
diegene die de bug mag fixen zal je dankbaar zijn
vb:
- frenoy match id (kan gebruikt worden op elke omgeving)
- database id en omgeving
- stappen om te reproduceren (hier niet van toepassing:)

anyhow, ziet er nu wel goed uit
ik heb wel nog synchronisatie code toegevoegd in de backend overlaatst, deze match was mss een dat verkeerd gesynced was

sluiten en hopen dat het niet terugkeert :p
