### ISSUE TITLE
links pagina herbekijken

### ISSUE THREAD

**Issue by Laoujin** [TTCErembodegem/TTC-React-Front#7]
* [ ] Sponsors ook opnemen op de links pagina (dan staan die toch al ergens)

**Comment by JornHeyvaert** [comment]
Ik zou deze opnemen in de site, maar dan met werkende links.
Kan altijd interessant zijn en is een shortcut naar VTTL of Sporta bijvoorbeeld e
Maakt de site denk ik ook aantrekkelijker

**Comment by JornHeyvaert** [comment]
- Officiele competitie (VTTL en Sporta)
- Frenoy
- Francis TT Shop
- Klassementberekening
- ITTF
