### ISSUE TITLE
dev: match ophalen en details bekijken

### ISSUE THREAD

**Issue by Laoujin** [TTCErembodegem/TTC-React-Front#76]
in some admin screen: put an inputfield & button
enter a match ID or a frenoy match id, fetch the data and goto the MatchCard

**Comment by JornHeyvaert** [comment]
Ben hiermee begonnen, maar zit wat vast.
Als je wilt, kan je dan eens de code bekijken (en testen?) op mijn branch en kijken wat er moet veranderd worden en hoe?
Wat met lege strings, fouten,....?

**Comment by Laoujin** [comment]
Als je momenteel rechten hebt als "DEV" dan zie je op een match een <pre>match JSON</pre>

Ik was meer aan het denken om in de Admin pagina een "DEV" tab toe te voegen waarin je de huidige state kan bekijken (ie: teams, clubs, players, matches, config, user, readonlymatches, ...) in zo'n <pre>
en met een filter erboven zodat je daar dan snel een MatchId of FrenoyMatchId ofzo kan ingeven om te filteren (of voor spelers een "Naam" of "Alias", ...)

**Comment by JornHeyvaert** [comment]
Das toch iets helemaal anders dan dat er hier beschreven staat? :P

**Comment by JornHeyvaert** [comment]
Dan is het eigenlijk hetzelfde tonen als de admin tab in de matchcard , maar dan een ID ingeven en dan de data tonen (de JSON)?

**Comment by Laoujin** [comment]
ik weet het :)
hetgeen er beschreven staat zit er eigenlijk al min of meer in: als je gewoon naar de url gaat van een match, dan gaat hij die match al gaan ophalen...

maar bedoeling is om hetgeen in de state zit te tonen (ie @connect alles en dan in een pre tonen)
en een extra zou daarbij zijn om een match id in te geven en als het nog niet in de state zit, het dan ook te gaan ophalen (er is al een fetchMatch function)

**Comment by JornHeyvaert** [comment]
Aja. En hoe moet ik daaraan beginnen dan?

**Comment by Laoujin** [comment]
Bijvoorbeeld:

![jorndevmockup](https://cloud.githubusercontent.com/assets/2582910/17649425/7bc58b4a-6235-11e6-9c4c-4134dbff4a8e.png)

**Comment by JornHeyvaert** [comment]
En dan moet alle matchen, clubs, teams,... in JSON getoond worden waarin ge dan kunt filteren? 
En wat met die fetch match? Die gaat dan naar de MatchCard fzo?

**Comment by Laoujin** [comment]
alle clubs, spelers en teams zitten in de state
maar niet alle matchen, dus voor matchen alles tonen wat in de state zit (ie: met @ connect decorator) + zo'n fetch --> eenmaal gefetched wordt die dan ook automatisch in de pre getoond

een uitvoeren knop is meer werk dan gewoon de filter... dus ik zou zonder button doen en direct filteren

**Comment by JornHeyvaert** [comment]
Zit voorlopig weer vast,

Ik krijg geen props of state in mijn AdminDev pagina/object.
Heb gezocht in code (vergeleken met andere pagina's, enz.) maar vind geen reden of fout
Misschien weet jij hier meer van?
Zie nieuwe code in zojuist gecommitte commit op mijn branch :)

Dit zit in het object voorlopig:
![image](https://cloud.githubusercontent.com/assets/10796411/17666306/f96adcf6-62ff-11e6-8d55-e806440725e6.png)

**Comment by Laoujin** [comment]
Geen bind op de event handler.
De fix is `onClick={::this._handler}`

Ik heb een pull request gemaakt

**Comment by JornHeyvaert** [comment]
Voor de matchen: Alle matchen laden gaat niet want dan loopt mijn computer gewoon vast :P. Enige suggesties?

**Comment by Laoujin** [comment]
hehehe...

gaan zou ik zeggen...
mss dat je als er teveel zijn, dat het gewoon een "pre" tag is, maar als je filtert en er zijn er niet zoveel meer dan switchen naar de json viewer (of switchen met een knopje)

je moet natuurlijk ook bekijken of die viewsers wel praktisch zijn...

**Comment by JornHeyvaert** [comment]
Hoe bedoelde? Twee views met een view met pre tag en een view met Inspector of TableInspector? En wat bedoelde met gaan? :P

**Comment by Laoujin** [comment]
gaan betekent... (er voor) gaan!

ik ken die packages niet zunne... je moet es checken: als je visualised met een van die twee (of een ander) package en dat ziet er goed uit: gebruiken. Als je zoiets hebt van "uhoh, die pre is eigenlijk duidelijker", dan niet gebruiken....


das trouwens zo'n ding met NPM: als je iets wil doen, de kans is groot dat het al bestaat... (vb een foto opladen, daarvoor heb ik gebruikt: react-dropzone en daarna om de foto bij te knippen zoals in facebook: react-avatar-editor... tis te gek om dergelijke dingen (cross-browser...) zelf te gaan ontwikkelen :)

**Comment by JornHeyvaert** [comment]
Ok. In verband met filtering. Is de filtering wel mogelijk aangezien de filtering wordt gedaan op basis van naam van velden bv. filter spelerID == text da is ingegeven in veld). Zoals het nu is kan men de filtering op alles uitvoeren dus wat moet hiermee gebeuren?. 

In geval van verschillende filters per tab:

- Hoe deze verschillende filters implementeren aangezien deze tabs allen hetzelfde component gebruiken? Dit component volsteken met zeer veel filters fzo?

**Comment by Laoujin** [comment]
Een generiek component volstoppen met iets is altijd een slecht idee.
Een switch (type) {  case 'spelers': case 'matches': case 'teams' } is ook altijd een slecht idee.

Een elegante oplossing voor dergelijke code is bijvoorbeeld:
<Component data={data} filter={matchesFilter} />
<Component data={data} filter={teamsFilter} />
Open/Closed Principle heet dat...


Maar het is wss nog makkelijker om gewoon een generieke filter te schrijven
Je loopt over alle properties van het object en dan filter je op die manier...

**Comment by JornHeyvaert** [comment]
Een generieke filter?

**Comment by Laoujin** [comment]
```
for each row in data
  for each property in row
     if property matches filter
         return true
return false
```
