### ISSUE TITLE
mobile windows phone: updating scores

### ISSUE THREAD

**Issue by Laoujin** [TTCErembodegem/TTC-React-Front#79]
Updating the scores does not seem to be working on Windows Phone

**Comment by Laoujin** [comment]
profile -> ploegopstelling lijkt ook niet te werken (wss zelfde issue?)

**Comment by Laoujin** [comment]
@JornHeyvaert : check jij dit nog eens? waarschijnlijk is het probleem met het updaten van material-ui, redux, react etc gewoon opgelost (de problemen waren met iphone ook grotendeels opgelost)

**Comment by JornHeyvaert** [comment]
Ploegopstelling kan ik een keer updaten. Maar daarna gaat het niet meer. Gaat altijd terug naar vorige status (tenzij ik de browser sluit en site opnieuw open)

**Comment by JornHeyvaert** [comment]
Ook de pagina update niet echt (speelweek) automatisch. Maar pas bij een refresh van pagina

**Comment by Laoujin** [comment]
Jammer, had gehoopt dat we er vanaf waren...

Kun jij deze bug opnemen?
... aangezien jij effectief een Windows Phone hebt...

**Comment by JornHeyvaert** [comment]
Na wat prutsen en per ongeluk wat wijzigingen gedaan te hebben op Productie-omgeving. (Heb het al aangepast op Productie-omgeving in den databank, kwist ni dat de ploegopstelling nu al definitief is als ge op knop drukt :p ) Kan ik zeggen dat het ploegopstelling probleem op Windows Phone niet voorvalt op Test-omgeving van onze site

**Comment by JornHeyvaert** [comment]
**Updating the scores does not seem to be working on Windows Phone**

Kan ik niet testen aangezien ik de volgende fout krijg als ik de testDB wil openen in HeidiSQL:

**User 'b521c082a57d8f' has exceeded the 'max_user_connections' resource (current value: 4)**

**Comment by JornHeyvaert** [comment]
**Aangeven of kan spelen of niet Bug in Windows Phone in Ploegopstelling tab in Profiel**

-> probleem treedt ook op Test-omgeving op mijn WP

**Comment by Laoujin** [comment]
Ok betere versies op TST en PRD gezet
Credentials van TST doorgestuurd

Als je logging wil doen:
-> Op TST zit in de index.html een lijn code van JSConsole
`<script src="http://jsconsole.com/js/remote.js?871544a7-a529-416a-84b7-b07bc380930f"></script>`

Als je naar jsconsole.com gaat en daar doet: `listen 871544a7-a529-416a-84b7-b07bc380930f`

Dan gaan alle console.logs die op de site gebeuren daar getoond worden.
Ik heb de iPhone stuff zo zitten debuggen...

**Comment by JornHeyvaert** [comment]
Heb het gedaan via die jsconsole.com. Krijg spijtig genoeg geen errors te zien. Heb het gedaan met de emulator. Misschien is proberen op mijne WP zelf als da gaat

**Comment by Laoujin** [comment]
Hehe.. Lang genoeg gewacht en nu is Windows Phone echt niet meer relevant :)
